#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <time.h>

#include <signal.h>
#include <unistd.h>

#include <vtrenderlib.h>

// Boid dimentions in dots.
#define VT_BOID_WIDTH   8
#define VT_BOID_LENGTH  12

// Boid linear speed in dots per second.
#define VT_BOID_SPEED        50

// Boid roll angle for banking in degrees.
// Larger angles produce sharper turns.
#define VT_BOID_BANK_ANGLE   60

// Wandering configuration.
#define VT_BOID_AVG_HEADING_DELAY_MS        2000
#define VT_BOID_HEADING_DELAY_VARIATION_MS  500
#define VT_BOID_HEADING_CHANGE_LIMIT_DEG    30

struct vec2f
{
    float x;
    float y;
};

struct vt_boid
{
    // position, velocity and normal vectors of a boid, normals are unit vectors (len is 1).
    struct vec2f p;
    struct vec2f v;
    struct vec2f n;

    // heading angle, in radians
    float heading;
    float desired_heading;

    // wandering state
    int heading_change_delay;
    int cur_heading_time;
};

static struct vtr_canvas* g_vt;
static struct vt_boid g_boid;

static inline float grad2rad(int grad)
{
    return M_PI * grad / 180;
}

static inline struct vec2f vec2f_mul_add(struct vec2f a, struct vec2f b, int scale)
{
    return (struct vec2f){a.x + b.x * scale, a.y + b.y * scale};
}

static inline struct vec2f vec2f_sub(struct vec2f a, struct vec2f b)
{
    return (struct vec2f){a.x - b.x, a.y - b.y};
}

static inline struct vec2f vec2f_unit(struct vec2f v)
{
    float m = sqrtf(v.x * v.x + v.y * v.y);
    assert(m != 0);

    return (struct vec2f){v.x / m, v.y / m};
}

static inline struct vec2f vec2f_normal(struct vec2f v)
{
    return (struct vec2f){-v.y, v.x};
}

static inline struct vec2f vec2f_rot(struct vec2f v, double rad)
{
    float cs = cosf(rad);
    float sn = sinf(rad);

    return (struct vec2f){
        v.x * cs - v.y * sn,
        v.x * sn + v.y * cs
    };
}

static inline struct vtr_vertex vec2f_project(struct vec2f v)
{
    return (struct vtr_vertex){(int)(v.x + 0.5f), (int)(v.y + 0.5f)};
}

static inline int random_value_in_range(int base, int variation)
{
    return base + ((rand() % (variation * 2)) - variation);
}

// Implements random wandering for a boid with no neighbours in view range.
// Gets called every frame to apply random gradual changes to boid's heading and follow them.
static void wander(struct vt_boid* b, int dtime)
{
    b->cur_heading_time += dtime;

    // See if we've been using our current target heading for enough time and change it if needed
    if (b->cur_heading_time >= b->heading_change_delay) {
        b->cur_heading_time = 0;
        b->heading_change_delay = random_value_in_range(VT_BOID_AVG_HEADING_DELAY_MS, VT_BOID_HEADING_DELAY_VARIATION_MS);
        b->desired_heading = b->heading + grad2rad(random_value_in_range(0, VT_BOID_HEADING_CHANGE_LIMIT_DEG));
    }
}

// Update heading to be closer to the desired heading over dt.
static float bank(struct vt_boid* b, int dtime)
{
    if (b->heading == b->desired_heading) {
        return 0.0f;
    }

    // The math below approximates bird banking by integrating radial force
    // generated by a fixed roll angle over dt.
    float phi = grad2rad(VT_BOID_BANK_ANGLE);
    float omega = (9.81 * tanf(phi)) / VT_BOID_SPEED;
    float dheading = omega * dtime / 1000;

    float heading = b->heading;
    if (fabsf(b->heading - b->desired_heading) <= dheading) {
        b->heading = b->desired_heading;
    } else {
        b->heading += (b->desired_heading > b->heading ? dheading : -dheading);
    }

    return b->heading - heading;
}

// Update simulation, dt is in millisecs.
static void update(double dtime)
{
    // TODO: only wander if no boids are nearby
    wander(&g_boid, (int)dtime);
    float dheading = bank(&g_boid, (int)dtime);

    g_boid.p.x += VT_BOID_SPEED * cosf(g_boid.heading) * dtime / 1000;
    g_boid.p.y += VT_BOID_SPEED * sinf(g_boid.heading) * dtime / 1000;
    g_boid.v = vec2f_rot(g_boid.v, dheading);
    g_boid.n = vec2f_normal(g_boid.v);

    // Wrap over screen edges
    if (g_boid.p.x < 0) {
        g_boid.p.x = vtr_xdots(g_vt) + g_boid.p.x;
    } else if (g_boid.p.x >= vtr_xdots(g_vt)) {
        g_boid.p.x = g_boid.p.x - vtr_xdots(g_vt);
    }

    if (g_boid.p.y < 0) {
        g_boid.p.y = vtr_ydots(g_vt) + g_boid.p.y;
    } else if (g_boid.p.y >= vtr_ydots(g_vt)) {
        g_boid.p.y = g_boid.p.y - vtr_ydots(g_vt);
    }
}

static void draw(void)
{
    struct vtr_vertex buf[] = {
        vec2f_project(vec2f_mul_add(g_boid.p, g_boid.n, -VT_BOID_WIDTH / 2)),
        vec2f_project(vec2f_mul_add(g_boid.p, g_boid.n, VT_BOID_WIDTH / 2)),
        vec2f_project(vec2f_mul_add(g_boid.p, g_boid.v, VT_BOID_LENGTH)),
    };

    vtr_trace_poly(g_vt, 3, buf);
}

static void restore_tty_attrs(void)
{
    vtr_close(g_vt);
}

static void handle_signal(int signo)
{
    if (signo == SIGWINCH) {
        vtr_set_resize_pending(g_vt);
    } else {
        restore_tty_attrs();
        signal(signo, SIG_DFL);
        raise(signo);
    }
}

int main(void)
{
    int error;

    g_vt = vtr_canvas_create(STDOUT_FILENO);
    if (!g_vt) {
        exit(EXIT_FAILURE);
    }

    atexit(restore_tty_attrs);
    signal(SIGINT, handle_signal);
    signal(SIGWINCH, handle_signal);

    error = vtr_reset(g_vt);
    if (error) {
        exit(error);
    }

    g_boid.p = (struct vec2f){50, 50};
    g_boid.v = (struct vec2f){1.0, 0.0};
    g_boid.n = vec2f_normal(g_boid.v);

    srand((unsigned int)time(NULL));

    while (true) {
        vtr_resize(g_vt);
        update(1000.0 / 60);
        draw();
        vtr_swap_buffers(g_vt);
        usleep(1000000 / 60);
    }

    return 0;
}
